version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URL: mongodb://mongo_db:27017/sample-db
    depends_on: 
      - mongo_db

  init_data:
    build:
      context: .
    depends_on:
      - mongo_db
    command: ["node", "populate.js"]
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_URL: mongodb://mongo_db:27017/sample-db

volumes:
  mongo_data: {}